sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem install bundler -v 1.16.2
script:
  - bundle exec rake ci
